/* eslint-disable */
/* Auto-generated by scripts/gen-types.mjs — do not edit by hand.
 * Regenerate via `npm run gen:types` (also runs on every commit). */

/**
 * Per-site configuration for the WCAG-EM-aligned automated accessibility testing toolkit. Validated by Ajv at config-load; see docs/adr/0002-config-is-ajv-validated.md.
 */
export interface WCAGEMAccessibilityToolkitConfig {
  /**
   * Short identifier for this audit run; appears in reports. Must contain at least one non-whitespace character.
   */
  name: string;
  /**
   * Absolute URL of the site root; discovery begins here.
   */
  rootUrl: string;
  scope: {
    /**
     * Crawl scope discipline. `same-hostname` (default) is safest for public sites.
     */
    mode: "same-hostname" | "same-origin" | "allowed-hosts";
    /**
     * Extra hostnames when mode is `allowed-hosts`.
     */
    allowedHosts?: string[];
    /**
     * Legacy field retained for backcompat; prefer `allowed-hosts` mode.
     */
    includeSubdomains?: boolean;
  };
  crawl: {
    maxPages?: number;
    maxConcurrency?: number;
    requestTimeoutSecs?: number;
    /**
     * Politeness throttle between requests.
     */
    requestDelayMs?: number;
    /**
     * Regex source strings; validated at load by the `validRegex` custom keyword.
     */
    excludeUrlPatterns?: string[];
    sitemapSeeding?: {
      enabled?: boolean;
      urls?: string[];
      commonPaths?: string[];
      maxUrls?: number;
    };
  };
  discovery?: {
    captureH1?: boolean;
    captureCanonical?: boolean;
    captureForms?: boolean;
    captureLandmarks?: boolean;
    captureSearchInputs?: boolean;
  };
  sample: {
    /**
     * Evaluator-chosen sample URLs (WCAG-EM Step 3a).
     */
    structuredManual?: string[];
    autoSuggest?: {
      enabled?: boolean;
      perCluster?: number;
      preferTypes?: (
        | "homepage"
        | "form-or-contact"
        | "policy"
        | "listing"
        | "detail"
        | "content"
        | "search-or-results"
        | "process-entry"
      )[];
    };
    randomPercentOfStructured?: number;
    minRandomPages?: number;
    /**
     * Recorded in metadata; same seed reproduces the same sample (WCAG-EM Step 3b).
     */
    randomSeed?: number;
    smallSiteSupplementaryScanThreshold?: number;
  };
  scan: {
    /**
     * Legacy single-viewport; prefer `viewports` (Layer 3a).
     */
    viewport?: {
      width?: number;
      height?: number;
      [k: string]: unknown;
    };
    /**
     * @minItems 1
     */
    viewports?: [
      {
        id: string;
        width: number;
        height: number;
      },
      ...{
        id: string;
        width: number;
        height: number;
      }[]
    ];
    waitUntil?: "load" | "domcontentloaded" | "networkidle" | "commit";
    timeoutMs?: number;
    retries?: number;
    fullPageScreenshots?: boolean;
    /**
     * Pre-scan hooks for cookie-consent dismissal, modal close, hydration waits.
     */
    beforeScan?: {
      actions?: Action[];
    };
    axe?: {
      include?: string[];
      exclude?: string[];
      withRules?: string[];
      withTags?: string[];
      runOnly?: null | {
        type: "tag" | "rule";
        /**
         * @minItems 1
         */
        values: [string, ...string[]];
      };
      /**
       * Per-URL axe-config overrides matched by `urlPattern`.
       */
      overrides?: {
        urlPattern: string;
        include?: string[];
        exclude?: string[];
        withRules?: string[];
        withTags?: string[];
        runOnly?: null | {
          type: "tag" | "rule";
          values: string[];
          [k: string]: unknown;
        };
        actions?: Action[];
      }[];
    };
  };
  processes?: {
    name: string;
    startUrl: string;
    pattern?: ("blank-submit" | "partial-submit") | null;
    forceInclude?: boolean;
    relatedUrls?: string[];
    steps?: Action[];
    selectors?: {
      [k: string]: string;
    };
    fields?: {
      selector: string;
      value?: string;
      [k: string]: unknown;
    }[];
    stepTimeoutMs?: number;
  }[];
  reporting?: {
    reporters?: ("json" | "markdown" | "html" | "earl-jsonld" | "junit")[];
    includePasses?: boolean;
    groupBestPracticeSeparately?: boolean;
    /**
     * Legacy alias for `reporters: [markdown]`; ignored when `reporters` is set.
     */
    markdownReport?: boolean;
    screenshotFormat?: "png" | "jpeg";
    screenshotQuality?: number;
    failOnFindings?: {
      impacts?: ("critical" | "serious" | "moderate" | "minor")[];
      classifications?: ("primary-automated-finding" | "best-practice-or-manual-review")[];
      threshold?: number;
    };
  };
  auth?: {
    storageState?:
      | string
      | {
          [k: string]: unknown;
        };
    httpCredentials?: {
      username: string;
      password: string;
    };
    setupScript?: string;
    ttlMinutes?: number;
    extraHttpHeaders?: {
      [k: string]: string;
    };
  };
  /**
   * WCAG-EM Step-5 report fields.
   */
  wcagEm?: {
    evaluator?: {
      name?: string;
      contact?: string;
    };
    wcagVersion?: "2.0" | "2.1" | "2.2";
    conformanceTarget?: "A" | "AA" | "AAA";
    atBaseline?: string[];
    technologiesReliedUpon?: string[];
    samplingMethodNotes?: string;
  };
}
export interface Action {
  action: "goto" | "click" | "fill" | "press" | "waitFor" | "screenshot" | "axe";
  url?: string;
  selector?: string;
  value?: string;
  key?: string;
  name?: string;
  state?: string;
  timeoutMs?: number;
  urlPattern?: string;
}
