// @ts-check
/**
 * @file Regenerate `src/types/config.d.ts` from `schemas/config.schema.json`.
 * @module scripts/gen-types
 *
 * @description
 * Runs on every commit via `.husky/pre-commit` so the generated TypeScript
 * declaration always matches the JSON schema. The committed file is the
 * source of truth for programmatic API consumers importing
 * `'wcag-em-a11y-toolkit'` with full type information.
 *
 * Safe to run by hand:  `npm run gen:types`
 *
 * @see docs/adr/0001-project-conventions.md
 * @see docs/adr/0005-fail-fast-on-config.md
 */

// SECTION: Imports
import fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { compileFromFile } from 'json-schema-to-typescript';

// SECTION: Paths
const __dirname = path.dirname(fileURLToPath(import.meta.url));
const SCHEMA_PATH = path.resolve(__dirname, '../schemas/config.schema.json');
const OUT_PATH = path.resolve(__dirname, '../src/types/config.d.ts');

// SECTION: Main
const ts = await compileFromFile(SCHEMA_PATH, {
  bannerComment:
    '/* eslint-disable */\n/* Auto-generated by scripts/gen-types.mjs — do not edit by hand.\n * Regenerate via `npm run gen:types` (also runs on every commit). */',
});
await fs.writeFile(OUT_PATH, ts);
console.log(`wrote ${path.relative(process.cwd(), OUT_PATH)}`);
